services:
  frontend:
    build:
      context: .
      dockerfile: ./containers/frontend.Dockerfile
      target: dev
    stop_signal: SIGINT
    profiles:
      - dev
    volumes:
      - ./system/frontend/:${FRONTEND_SRC_DIR:-/opt/builder}
      - shared_build:/opt/builder/dist

  backend:
    build:
      context: .
      dockerfile: ./containers/backend.Dockerfile
      target: dev
      additional_contexts:
        system: ./system
    stop_signal: SIGINT
    profiles:
      - dev
    ports:
      - 127.0.0.1:${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}
    volumes:
      - ./system/backend/:${BACKEND_SRC_DIR:-/opt/app}
      - shared_build:/opt/app/static
    
  app:
    build:
      context: .
      dockerfile: ./containers/backend.Dockerfile
      target: prod
      additional_contexts:
        system: ./system
    stop_signal: SIGINT
    profiles:
      - prod
    ports:
      - 127.0.0.1:${BACKEND_PORT:-5000}:${BACKEND_PORT:-5000}

volumes:
  shared_build: